### Invoke the llm generator
POST http://localhost:8000/llm/invoke
Content-Type: application/json

{
  "input": {
    "topic": "Can you tell me a little about Cristiano Ronaldo?",
    "image":""
  }
}

### create user
POST http://localhost:8000/user
Content-Type:  application/json

{
    "firstname":"Nasim",
    "lastname":"Nazari",
    "email":"n.nazari@gmail.com",
    "password":"Admin4320!"
}

### Get Users
GET http://localhost:8000/user
Content-Type:  application/json